version: 2.1
jobs:
  build_test:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout # checkout source code to working directory
      - run:
          command: | # create whl and use pipenv to install dependencies
            sudo add-apt-repository universe -y
            sudo apt-get update
            sudo apt install -y python3-pip
            sudo pip install pipenv
            make evnn_pytorch # Build PyTorch API
            pipenv install evnn_pytorch-*.whl
      - run:
          command: | # Run test suite
            python -m unittest discover -p '*_test.py' -s validation

workflows:
  build_test_publish:
    jobs:
      - build_test

